target 'iosTrila' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'frontend', :path => '../frontend'
end

# Fix Xcode warning: build phase '[CP] Copy XCFrameworks' will be run during every build
# Ref.: https://github.com/CocoaPods/CocoaPods/issues/11444
def set_run_script_to_always_run_when_no_input_or_output_files_exist(project:)
  project.targets.each do |target|
    run_script_build_phases = target.build_phases.filter { |phase| phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase) }
    cocoapods_run_script_build_phases = run_script_build_phases.filter { |phase| phase.name.start_with?("[CP") }
    cocoapods_run_script_build_phases.each do |run_script|
      next unless (run_script.input_paths || []).empty? && (run_script.output_paths || []).empty?
      run_script.always_out_of_date = "1"
    end
  end
  project.save
end

post_integrate do |installer|
  main_project = installer.aggregate_targets[0].user_project
  set_run_script_to_always_run_when_no_input_or_output_files_exist(project: main_project)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Projects usually do stuff in here…
  end
  set_run_script_to_always_run_when_no_input_or_output_files_exist(project: installer.pods_project)
end
